version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    container_name: bot-mogndodb
    volumes:
      - E:/Programming/MongoDB/Server/6.0/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always 
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot:1.3.0
    container_name: bot
    volumes:
      - /home/node/node_modules
      - E:/Programming/DoingSomething/ortkReports_bot:/home/node
      - D:/bot:/home/bot/
    env_file:
      - .env

